name: App build Workflow

on:
  workflow_call:

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          cd program/sw-site/
          mvn package -DskipTests=true
          cd ${{ github.workspace }}/program/sw-site/sw-site-web/target/
          ls

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sw-site-web-1.jar
          path: ${{ github.workspace }}/program/sw-site/sw-site-web/target/sw-site-web-1.jar

  image-build:
    runs-on: ubuntu-latest
    needs: java-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sw-site-web-1.jar
          path: .

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: ${{ github.workspace }}/Dockerfile
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
